# Generated by Django 2.0 on 2020-02-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='published_date',
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
