# Generated by Django 2.0 on 2020-02-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='author',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
