# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QTextCharFormat, QPalette
from PyQt5.QtCore import Qt, QDate, QRectF
from PyQt5.QtWidgets import QScrollArea, QSizePolicy


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 650)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.centralwidget.setBackgroundRole(QPalette.)

        #사진 저장
        self.image_save = QtWidgets.QPushButton(self.centralwidget)
        self.image_save.setGeometry(QtCore.QRect(1190, 600, 101, 41))
        self.image_save.setObjectName("image_save")
        self.image_save.clicked.connect(self.image_copy)
        #암 등급 예측
        self.image_cancer_predict = QtWidgets.QPushButton(self.centralwidget)
        self.image_cancer_predict.setGeometry(QtCore.QRect(950, 600, 101, 41))
        self.image_cancer_predict.setObjectName("image_cancer_predict")
        self.image_cancer_predict.clicked.connect(self.cancer_grade_predict)
        #암세포 영역 에측
        self.image_search_cancer = QtWidgets.QPushButton(self.centralwidget)
        self.image_search_cancer.setGeometry(QtCore.QRect(1070, 600, 101, 41))
        self.image_search_cancer.setObjectName("image_search_cancer")
        self.image_search_cancer.clicked.connect(self.cancer_grade_segment)
        #암 등급 예측 값
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(820, 600, 111, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        # 사진 보여주는 창
        # self.image_view = QtWidgets.QLabel(self.centralwidget)
        # self.image_view.setGeometry(QtCore.QRect(330, 20, 491, 491))
        # self.image_view.setObjectName("label")
        # self.image_view.setBackgroundRole(QPalette.Base)
        # self.image_view.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        # self.image_view.setScaledContents(True)
        # 사진창 스크롤
        # self.scrollArea = QScrollArea()
        # self.scrollArea.setBackgroundRole(QPalette.Dark)
        # self.scrollArea.setWidget(self.image_view)
        # self.setCentralWidget(self.scrollArea)
        #사진 보여주는 창
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(330, 10, 960, 580))
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        # self.graphicsView.fitInView(QRectF(0, 0, 491, 491), Qt.KeepAspectRatio)
        self.graphicsView.setObjectName("graphicsView")


        #830 10
        self.plusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton.setGeometry(QtCore.QRect(1230, 450, 31, 31))
        self.plusButton.setObjectName("plusButton")
        self.plusButton.clicked.connect(self.image_size_up)

        self.minusbutton = QtWidgets.QPushButton(self.centralwidget)
        self.minusbutton.setGeometry(QtCore.QRect(1230, 490, 31, 31))
        self.minusbutton.setObjectName("minusbutton")
        self.minusbutton.clicked.connect(self.image_size_down)

        self.originbutton = QtWidgets.QPushButton(self.centralwidget)
        self.originbutton.setGeometry(QtCore.QRect(1230, 530, 31, 31))
        self.originbutton.setObjectName("originbutton")
        self.originbutton.clicked.connect(self.origin_image_size)

        #달력
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 10, 310, 200))
        self.calendarWidget.setObjectName("calendarWidget")
        # 달력 오늘 날짜
        calendar_today_style = QTextCharFormat()
        calendar_today_style.setForeground(Qt.red)
        calendar_today_style.setBackground(Qt.yellow)
        self.calendarWidget.setDateTextFormat(QDate.currentDate(), calendar_today_style)

        #달력 action
        self.calendarWidget.clicked.connect(self.calendar_date)
        # self.select_day = self.calendarWidget.selectedDate()
        #환자 목록 새로고침
        self.re_patient_list = QtWidgets.QPushButton(self.centralwidget)
        self.re_patient_list.setGeometry(QtCore.QRect(240, 380, 81, 31))
        self.re_patient_list.setObjectName("re_patient_list")
        self.re_patient_list.clicked.connect(self.startFound)
        #환자 검색
        self.search_patient = QtWidgets.QPushButton(self.centralwidget)
        self.search_patient.setGeometry(QtCore.QRect(152, 380, 81, 31))
        self.search_patient.setObjectName("search_patient")
        self.search_patient.clicked.connect(self.search_patient_list)

        #환자 검색 창
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 380, 131, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.patient_list = QtWidgets.QTreeView(self.centralwidget)
        self.patient_list.setGeometry(QtCore.QRect(10, 220, 310, 150))
        self.patient_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.patient_list.setObjectName("patient_list")
        self.patient_list.setRootIsDecorated(False)
        self.patient_list.setAlternatingRowColors(True)

        self.info = QStandardItemModel(0,3,self)
        self.info.setHeaderData(0, Qt.Horizontal, "환자번호")
        self.info.setHeaderData(1, Qt.Horizontal, "  이   름")
        self.info.setHeaderData(2, Qt.Horizontal, "생년월일")

        self.patient_list.setModel(self.info)
        self.patient_list.setColumnWidth(0, 60)
        self.patient_list.setColumnWidth(1, 60)
        self.patient_list.setColumnWidth(2, 60)

        self.patient_list.clicked.connect(self.find_patient_image_list)


        self.patient_image = QtWidgets.QTreeView(self.centralwidget)
        self.patient_image.setGeometry(QtCore.QRect(10, 420, 310, 170))
        self.patient_image.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.patient_image.setObjectName("patient_cancer_image")
        self.patient_image.setRootIsDecorated(False)
        self.patient_image.setAlternatingRowColors(True)

        self.info_image = QStandardItemModel(0, 3, self)
        self.info_image.setHeaderData(0, Qt.Horizontal, "검사일")
        self.info_image.setHeaderData(1, Qt.Horizontal, "파일명")
        self.info_image.setHeaderData(2, Qt.Horizontal, "기타")

        self.patient_image.setModel(self.info_image)
        self.patient_image.setColumnWidth(0, 60)
        self.patient_image.setColumnWidth(1, 150)
        self.patient_image.setColumnWidth(2, 60)

        self.patient_image.clicked.connect(self.show_patient_image)



        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image_save.setText(_translate("MainWindow", "Save"))
        self.image_cancer_predict.setText(_translate("MainWindow", "Prediction"))
        self.image_search_cancer.setText(_translate("MainWindow", "Search"))
        self.re_patient_list.setText(_translate("MainWindow", "새로고침"))
        self.search_patient.setText(_translate("MainWindow", "검 색"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.minusbutton.setText(_translate("MainWindow", "-"))
        self.originbutton.setText(_translate("MainWindow", "⊙"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
